// Site texts (interface labels, section titles, fixed paragraphs), by permanent key.
// These are the defaults from the v12 design (data/ui-copy.json). A row with the same key in Airtable
// ("Textes du site", status Final) replaces the default: editors change texts there, never here.
// {name}-style variables are filled by the page. Copy rules (CLAUDE.md §11) are checked on these too.
export const COPY_DEFAULTS = {
  // Site
  'site.name': 'Rivières & Canyons Gwada',
  'site.mark': 'RC',
  'site.tagline': 'Répertoire indépendant des rivières et canyons de Guadeloupe',
  'nav.places': 'Les lieux',
  'nav.ideas': 'Idées de sorties',
  'nav.guides': 'Les guides',
  'nav.menu_open': 'Ouvrir le menu',
  'nav.menu_close': 'Fermer le menu',
  'nav.home': 'Accueil',
  'nav.breadcrumb': "Fil d'Ariane",
  'nav.back_to_results': '← Tous les résultats',

  // Place page
  'place.overview_eyebrow': 'Aperçu',
  'place.overview_title': '{name}',
  'place.key_facts': 'Bon à savoir',
  'place.when': 'Quand y aller',
  'place.also_called': 'Aussi appelé',
  'place.tip_team': "Le conseil de l'équipe",
  'place.tip_guide': 'Le conseil de {guide}',
  'place.photos_title': '{name} en photos',
  'place.photos_site': 'Sur place',
  'place.photos_guided': 'En sortie guidée avec {guide}',
  'place.photos_credit': 'Photos issues des sites cités dans nos sources, tous droits réservés à leurs auteurs.',
  'place.photos_sources': 'Voir les sources',
  'place.photo_previous': 'Photo précédente',
  'place.photo_next': 'Photo suivante',
  'place.photo_close': 'Fermer',
  'place.photo_missing': 'Photo à venir',
  'place.access_title_public': 'Comment aller à {name}',
  'place.access_title_commune': 'Où se trouve {name}',
  'place.access_title_guide': 'Accéder à {name} avec un guide',
  'place.access_title_closed': 'Accès : site fermé',
  'place.access_own': 'Par vos propres moyens',
  'place.access_maps': 'Ouvrir dans Google Maps',
  'place.access_commune_title': 'Commune : {commune}',
  'place.access_commune_text': "L'accès exact n'est pas publié : renseignez-vous sur place ou auprès de la mairie avant de partir.",
  'place.access_unknown_commune': 'Commune non confirmée',
  'place.access_guide_title': 'Point de rendez-vous donné par le guide',
  'place.access_guide_text': "Ce site se découvre avec un guide : il vous donne le lieu de rendez-vous à la réservation. Aucun itinéraire n'est publié ici.",
  'place.access_closed_title': "Pas d'itinéraire publié",
  'place.access_closed_text': "L'accès libre est interdit. Nous ne publions pas d'itinéraire vers ce site.",
  'place.access_go_with': 'Y aller avec {guide}',
  'place.access_status_checked': 'vérifié le {date}',
  'place.safety_title': 'Avant de partir : sécurité et équipement',
  'place.rules_title': 'Les règles en rivière',
  'place.rules_text': "Le niveau de l'eau peut monter en quelques minutes après une pluie en amont, même par temps clair. Ne descendez jamais seul un site technique. En cas de doute (eau trouble, débit qui monte), sortez du lit de la rivière.",
  'place.risks_title': 'Risques signalés sur ce site',
  'place.bring_title': 'Dans le sac',
  'place.no_guide': "Aucun guide partenaire ne propose ce site pour l'instant.",
  'place.no_guide_link': 'Voir les sorties guidées',
  'place.offer_title': 'Aller à {name} avec un guide',
  'place.offer_kind': 'Sortie guidée',
  'place.offer_programme': 'Programme',
  'place.offer_why': 'Pourquoi y aller avec {guide}',
  'place.offer_provided': 'Fourni par le guide',
  'place.offer_bring': 'À prévoir',
  'place.offer_highlights': 'Au programme',
  'place.offer_reviews': 'Avis sur la sortie avec {guide}',
  'place.offer_with': 'avec {guide} de {company}',
  'place.offer_from': 'dès',
  'place.offer_per_adult': '/ adulte',
  'place.offer_child': 'Enfant (moins de {age} ans) : {price}',
  'place.offer_book': 'Réserver',
  'place.offer_write': 'Écrire à {guide}',
  'place.offer_alternative': 'Autre sortie ici',
  'place.offer_since': 'Sur ce site depuis {year}',
  'place.offer_duration': 'Durée',
  'place.offer_min_age': 'Dès',
  'place.offer_level': 'Niveau',
  'place.offer_approach': 'Approche',
  'place.social_eyebrow': 'Réseaux sociaux',
  'place.social_title': '{name} sur les réseaux',
  'place.press_eyebrow': 'Ils en parlent',
  'place.press_title': 'Pour aller plus loin',
  'place.faq_title': '{name} : questions fréquentes',
  'place.nearby_title': 'Autres sites à proximité',
  'place.explore_title': 'Idées de sorties en Guadeloupe',
  'place.sources_title': 'Sources et crédits',
  'place.sources_source': 'Source',
  'place.sources_access': "État d'accès",
  'place.sources_photos': 'Photos',
  'place.estimate': 'À confirmer',
  'place.yes': 'Oui',
  'place.no': 'Non',
  'place.minutes': '{n} min',
  'place.hours': '{h} h',
  'place.hours_minutes': '{h} h {m}',
  'place.range': '{a} à {b}',
  'place.age': '{n} ans',
  'place.age_plus': '{n} ans +',
  'place.danger_badge': 'Alerte sécurité : voir les détails',

  // Guides block ("Qui sommes-nous")
  'team.eyebrow': 'Qui sommes-nous',
  'team.title': "Nous, c'est Pascal et Quentin",
  'team.text_1': "Deux guides professionnels, tombés amoureux des rivières et des canyons de Guadeloupe il y a quelques années. On n'a jamais réussi à arrêter d'en parler, alors on a décidé de les faire découvrir.",
  'team.text_2': "On a construit ce site pour recenser les rivières, canyons et cascades de l'île, avec les infos utiles pour y aller. Et si l'envie vous prend, vous pouvez partir avec l'un de nous.",
  'team.with': 'Avec {guide}',
  'team.profile': 'Voir le profil',
  'team.operator.yalode': 'La randonnée aquatique en douceur : bain de forêt, familles, groupes réduits. Pas de rappel imposé, tout est contournable.',
  'team.operator.wildcanyon': 'Les sensations fortes en sécurité : sauts, rappels, toboggans. Plus de 200 canyons explorés dans le monde.',
  'team.credential.yalode': "Brevet d'État, depuis 2012",
  'team.credential.wildcanyon': "DE JEPS, 8 ans d'expérience",

  // Legal notice and footer
  'legal.inline_summary': 'Annuaire informatif : à vérifier avant de partir',
  'legal.inline_text': "Ce site est un annuaire informatif. Il ne remplace ni vos propres vérifications, ni l'avis d'un professionnel, ni les règles en vigueur sur place. Vous restez seul responsable de vos choix et de votre sécurité.",
  'legal.inline_link': "Lire l'avertissement",
  'legal.full_summary': 'Avertissement',
  // Decision pending (docs/OPEN_LOOPS.md C1): the design said "pour ceux qui souhaitent découvrir ces lieux en sécurité",
  // a safety claim in the disclaimer (not allowed, CLAUDE.md §11). Neutral wording until Jordan decides.
  'legal.full_1': "Ce site a d'abord pour but de faire connaître les plus beaux sites naturels de Guadeloupe, rivières, cascades et canyons, avec les informations utiles pour chacun, que vous partiez seul ou accompagné. Les guides qui l'animent proposent aussi des sorties encadrées par des professionnels diplômés, pour ceux qui préfèrent découvrir ces lieux accompagnés.",
  'legal.full_2': 'Les informations publiées (accès, durées, niveaux, conditions, statut d\'ouverture) sont indicatives. Elles peuvent être incomplètes ou devenir inexactes, et ne sont pas garanties. En rivière, les conditions changent en quelques minutes.',
  'legal.full_3': "Avant toute sortie, renseignez-vous auprès des sources officielles (mairie, Parc national, préfecture, Météo-France). Respectez les arrêtés, la signalisation et les propriétés privées, et évaluez vos capacités. Les sorties guidées relèvent de la responsabilité de l'opérateur qui les organise.",
  'legal.full_4': "Toute activité en milieu naturel se pratique sous votre propre responsabilité. Les éditeurs de ce site ne peuvent être tenus responsables des accidents, dommages ou pertes liés à l'utilisation de ces informations.",
  // Decision pending (C2): the design's note starts with "Prototype indépendant…".
  'footer.independence': 'Site indépendant référençant Yalodé (kayak-guadeloupe.fr) et Wild Canyon (wild-canyon.fr). Tarifs et durées Wild Canyon repris de leur site ; communes, âges minimum et niveaux de forme sont des estimations à valider avec eux.',
  'footer.by_type': 'Par type',
  'footer.by_area': 'Par île',
  'footer.by_locality': 'Par commune',
  'footer.ideas': 'Idées de sorties',
  'footer.guides': 'Les guides',
  'footer.privacy': 'Politique de confidentialité',
  'footer.legal': 'Mentions légales',
  'footer.about': 'Qui sommes-nous',
  'footer.contact': 'Contact',

  // Contact (WhatsApp message, CLAUDE.md §9)
  'contact.whatsapp_message': 'Bonjour {guide}, je vous écris depuis {site} au sujet de {subject}.',
} as const;

export type CopyKey = keyof typeof COPY_DEFAULTS;
