// Site texts (interface labels, section titles, fixed paragraphs), by permanent key.
// These are the defaults from the v12 design (data/ui-copy.json). A row with the same key in Airtable
// ("Textes du site", status Final) replaces the default: editors change texts there, never here.
// {name}-style variables are filled by the page. Copy rules (CLAUDE.md §11) are checked on these too.
export const COPY_DEFAULTS = {
  // Site
  'site.name': 'Rivières & Canyons Gwada',
  'site.mark': 'RC',
  'site.tagline': 'Répertoire indépendant des rivières et canyons de Guadeloupe',
  'nav.places': 'Les lieux',
  'nav.ideas': 'Idées de sorties',
  'nav.guides': 'Les guides',
  'nav.menu_open': 'Ouvrir le menu',
  'nav.menu_close': 'Fermer le menu',
  'nav.home': 'Accueil',
  'nav.breadcrumb': "Fil d'Ariane",
  'nav.back_to_results': '← Tous les résultats',

  // Listing (home)
  'listing.title': 'Découvrez les plus belles rivières, canyons & chutes de Guadeloupe',
  'listing.description': 'Répertoire indépendant des rivières, canyons et cascades de Guadeloupe : accès, niveau, baignade, sécurité, et sorties avec un guide diplômé.',
  // Decision pending (docs/OPEN_LOOPS.md C3): the design said "et on vous accompagne en toute sécurité sur les plus sympas",
  // a safety claim on the listing (not allowed, CLAUDE.md §11). Neutral wording until Jordan decides.
  'listing.subtitle': 'On répertorie les canyons, rivières et cascades, et on vous accompagne sur les plus sympas.',
  'listing.operators': 'Excursions guidées proposées par',
  'listing.search_label': 'Rechercher un lieu ou une commune',
  'listing.search_placeholder': 'Un canyon, une commune…',
  'listing.filters': 'Filtres',
  'listing.filters_title': 'Filtres',
  'listing.filters_clear': 'Effacer',
  'listing.filters_show': 'Voir {n} résultats',
  'listing.filters_close': 'Fermer les filtres',
  'listing.results_title': 'Les lieux et les sorties guidées',
  'listing.results_one': '{n} résultat correspond',
  'listing.results_many': '{n} résultats correspondent',
  'listing.alert_title': 'Une rivière peut monter en quelques minutes.',
  'listing.alert_text': 'Même par temps clair, une pluie en amont suffit. Ne descendez jamais seul un site technique ; sur les sites non guidés, renseignez-vous avant de partir.',
  'listing.alert_badge': 'Attention',
  'listing.empty_title': 'Aucun lieu ne correspond',
  'listing.empty_text': 'Assouplissez un critère, ou dites-nous ce que vous cherchez.',
  'listing.empty_reset': 'Réinitialiser',
  'listing.empty_ask': 'Demander conseil à {guide}',
  'listing.cta_guided': 'Y aller en sécurité',
  'listing.cta_place': 'Plus d’infos',
  'listing.not_guided': 'Non guidé',
  'listing.with': 'avec {company}',
  'listing.guided_kind': 'Sortie guidée',
  'listing.price_child': '{adult} / {child} €',
  'listing.f_show': 'Afficher',
  'listing.f_show_all': 'Tout',
  'listing.f_show_guided': 'Excursions guidées',
  'listing.f_show_places': 'Les lieux',
  'listing.f_type': 'Type',
  'listing.f_level': 'Niveau',
  'listing.f_spirit': 'Esprit',
  'listing.f_guide': 'Guide',
  'listing.f_duration': 'Durée',
  'listing.f_half_day': 'Demi-journée',
  'listing.f_day': 'Journée',
  'listing.f_approach': "Marche d'approche",
  'listing.f_approach_15': '15 min ou moins',
  'listing.f_approach_30': '30 min ou moins',
  'listing.f_confidence': 'Fiabilité des infos',
  'listing.f_area': 'Île',
  'listing.f_kids': 'Adapté aux enfants',
  'listing.f_kids_hint': 'Dès 8 ans ou moins',
  'listing.f_guided_hint': 'Seulement les sorties avec un guide',
  'listing.sort': 'Trier',
  'listing.sort_default': 'Sorties guidées d’abord',
  'listing.sort_name': 'Nom',
  'listing.sort_price': 'Prix',
  'lead.eyebrow': 'Le top 5, par message',
  'lead.title': 'Notre top 5 des canyons, avec une petite surprise',
  'lead.text': "On vous l'envoie par e-mail. Votre numéro est facultatif, pour la surprise sur WhatsApp.",
  'lead.email': 'Votre e-mail',
  'lead.email_placeholder': 'votre e-mail',
  'lead.submit': 'Recevoir',
  'lead.consent': "J'accepte de recevoir le top 5 et les conseils de sortie de Pascal et Quentin par e-mail. Désinscription en un clic.",
  'lead.privacy': 'Politique de confidentialité',
  'lead.phone_text': 'Ajoutez votre numéro pour recevoir la surprise sur WhatsApp (facultatif)',
  'lead.phone_placeholder': 'votre numéro',
  'lead.phone_submit': 'Ajouter',
  'lead.phone_skip': 'Non merci',
  'lead.done': 'Le top 5 (et sa petite surprise) arrive vite.',
  'lead.error': "L'envoi n'a pas abouti. Vérifiez votre e-mail et réessayez dans un instant.",
  'lead.sending': 'Envoi…',

  // Place page
  'place.overview_eyebrow': 'Aperçu',
  'place.overview_title': '{name}',
  'place.key_facts': 'Bon à savoir',
  'place.when': 'Quand y aller',
  'place.also_called': 'Aussi appelé',
  'place.tip_team': "Le conseil de l'équipe",
  'place.tip_guide': 'Le conseil de {guide}',
  'place.photos_title': '{name} en photos',
  'place.photos_site': 'Sur place',
  'place.photos_guided': 'En sortie guidée avec {guide}',
  'place.photos_credit': 'Photos issues des sites cités dans nos sources, tous droits réservés à leurs auteurs.',
  'place.photos_sources': 'Voir les sources',
  'place.photo_previous': 'Photo précédente',
  'place.photo_next': 'Photo suivante',
  'place.photo_close': 'Fermer',
  'place.photo_missing': 'Photo à venir',
  'place.access_title_public': '{name} : comment y aller',
  'place.access_title_public_to': 'Comment aller {to}',
  'place.access_title_commune': 'Où se trouve {name}',
  'place.access_title_guide': '{name} : accès avec un guide',
  'place.access_title_guide_to': 'Accéder {to} avec un guide',
  'place.access_title_closed': 'Accès : site fermé',
  'place.access_own': 'Par vos propres moyens',
  'place.access_maps': 'Ouvrir dans Google Maps',
  'place.access_commune_title': 'Commune : {commune}',
  'place.access_commune_text': "L'accès exact n'est pas publié : renseignez-vous sur place ou auprès de la mairie avant de partir.",
  'place.access_unknown_commune': 'Commune non confirmée',
  'place.access_guide_title': 'Point de rendez-vous donné par le guide',
  'place.access_guide_text': "Ce site se découvre avec un guide : il vous donne le lieu de rendez-vous à la réservation. Aucun itinéraire n'est publié ici.",
  'place.access_closed_title': "Pas d'itinéraire publié",
  'place.access_closed_text': "L'accès libre est interdit. Nous ne publions pas d'itinéraire vers ce site.",
  'place.access_go_with': 'Y aller avec {guide}',
  'place.access_status_checked': 'vérifié le {date}',
  'place.safety_title': 'Avant de partir : sécurité et équipement',
  'place.rules_title': 'Les règles en rivière',
  'place.rules_text': "Le niveau de l'eau peut monter en quelques minutes après une pluie en amont, même par temps clair. Ne descendez jamais seul un site technique. En cas de doute (eau trouble, débit qui monte), sortez du lit de la rivière.",
  'place.risks_title': 'Risques signalés sur ce site',
  'place.bring_title': 'Dans le sac',
  'place.no_guide': "Aucun guide partenaire ne propose ce site pour l'instant.",
  'place.no_guide_link': 'Voir les sorties guidées',
  'place.offer_title': '{name} avec un guide',
  'place.offer_title_to': 'Aller {to} avec un guide',
  'place.offer_kind': 'Sortie guidée',
  'place.offer_programme': 'Programme',
  'place.offer_why': 'Pourquoi y aller avec {guide}',
  'place.offer_provided': 'Fourni par le guide',
  'place.offer_bring': 'À prévoir',
  'place.offer_highlights': 'Au programme',
  'place.offer_reviews': 'Avis sur la sortie avec {guide}',
  'place.offer_with': 'avec {guide} de {company}',
  'place.offer_from': 'dès',
  'place.offer_per_adult': '/ adulte',
  'place.offer_child': 'Enfant (moins de {age} ans) : {price}',
  'place.offer_book': 'Réserver',
  'place.offer_write': 'Écrire à {guide}',
  'place.offer_alternative': 'Autre sortie ici',
  'place.offer_since': 'Sur ce site depuis {year}',
  'place.offer_story': 'Pourquoi je vous emmène ici',
  'place.offer_about': 'À propos de {guide}',
  'place.offer_go': 'Y aller avec un guide',
  'place.account_unknown': 'compte à renseigner',
  'place.facts_label': 'Repères',
  'place.view': 'Voir',
  'place.offer_duration': 'Durée',
  'place.offer_min_age': 'Dès',
  'place.offer_level': 'Niveau',
  'place.offer_approach': 'Approche',
  'place.social_eyebrow': 'Réseaux sociaux',
  'place.social_title': '{name} sur les réseaux',
  'place.press_eyebrow': 'Ils en parlent',
  'place.press_title': 'Pour aller plus loin',
  'place.faq_title': '{name} : questions fréquentes',
  'place.nearby_title': 'Autres sites à proximité',
  'place.explore_title': 'Idées de sorties en Guadeloupe',
  'place.sources_title': 'Sources et crédits',
  'place.sources_source': 'Source',
  'place.sources_access': "État d'accès",
  'place.sources_photos': 'Photos',
  'place.estimate': 'À confirmer',
  'place.yes': 'Oui',
  'place.no': 'Non',
  'place.minutes': '{n} min',
  'place.hours': '{h} h',
  'place.hours_minutes': '{h} h {m}',
  'place.range': '{a} à {b}',
  'place.age': '{n} ans',
  'place.age_plus': '{n} ans +',
  'place.danger_badge': 'Alerte sécurité : voir les détails',

  // Guides block ("Qui sommes-nous")
  'team.eyebrow': 'Qui sommes-nous',
  'team.title': "Nous, c'est Pascal et Quentin",
  'team.text_1': "Deux guides professionnels, tombés amoureux des rivières et des canyons de Guadeloupe il y a quelques années. On n'a jamais réussi à arrêter d'en parler, alors on a décidé de les faire découvrir.",
  'team.text_2': "On a construit ce site pour recenser les rivières, canyons et cascades de l'île, avec les infos utiles pour y aller. Et si l'envie vous prend, vous pouvez partir avec l'un de nous.",
  'team.with': 'Avec {guide}',
  'team.profile': 'Voir le profil',
  'team.operator.yalode': 'La randonnée aquatique en douceur : bain de forêt, familles, groupes réduits. Pas de rappel imposé, tout est contournable.',
  'team.operator.wildcanyon': 'Les sensations fortes en sécurité : sauts, rappels, toboggans. Plus de 200 canyons explorés dans le monde.',
  'team.credential.yalode': "Brevet d'État, depuis 2012",
  'team.credential.wildcanyon': "DE JEPS, 8 ans d'expérience",

  // Legal notice and footer
  'legal.inline_summary': 'Annuaire informatif : à vérifier avant de partir',
  'legal.inline_text': "Ce site est un annuaire informatif. Il ne remplace ni vos propres vérifications, ni l'avis d'un professionnel, ni les règles en vigueur sur place. Vous restez seul responsable de vos choix et de votre sécurité.",
  'legal.inline_link': "Lire l'avertissement",
  'legal.full_summary': 'Avertissement',
  // Decision pending (docs/OPEN_LOOPS.md C1): the design said "pour ceux qui souhaitent découvrir ces lieux en sécurité",
  // a safety claim in the disclaimer (not allowed, CLAUDE.md §11). Neutral wording until Jordan decides.
  'legal.full_1': "Ce site a d'abord pour but de faire connaître les plus beaux sites naturels de Guadeloupe, rivières, cascades et canyons, avec les informations utiles pour chacun, que vous partiez seul ou accompagné. Les guides qui l'animent proposent aussi des sorties encadrées par des professionnels diplômés, pour ceux qui préfèrent découvrir ces lieux accompagnés.",
  'legal.full_2': 'Les informations publiées (accès, durées, niveaux, conditions, statut d\'ouverture) sont indicatives. Elles peuvent être incomplètes ou devenir inexactes, et ne sont pas garanties. En rivière, les conditions changent en quelques minutes.',
  'legal.full_3': "Avant toute sortie, renseignez-vous auprès des sources officielles (mairie, Parc national, préfecture, Météo-France). Respectez les arrêtés, la signalisation et les propriétés privées, et évaluez vos capacités. Les sorties guidées relèvent de la responsabilité de l'opérateur qui les organise.",
  'legal.full_4': "Toute activité en milieu naturel se pratique sous votre propre responsabilité. Les éditeurs de ce site ne peuvent être tenus responsables des accidents, dommages ou pertes liés à l'utilisation de ces informations.",
  // Decision pending (C2): the design's note starts with "Prototype indépendant…".
  'footer.independence': 'Site indépendant référençant Yalodé (kayak-guadeloupe.fr) et Wild Canyon (wild-canyon.fr). Tarifs et durées Wild Canyon repris de leur site ; communes, âges minimum et niveaux de forme sont des estimations à valider avec eux.',
  'footer.by_type': 'Par type',
  'footer.by_area': 'Par île',
  'footer.by_locality': 'Par commune',
  'footer.ideas': 'Idées de sorties',
  'footer.guides': 'Les guides',
  'footer.privacy': 'Politique de confidentialité',
  'footer.legal': 'Mentions légales',
  'footer.about': 'Qui sommes-nous',
  'footer.contact': 'Contact',

  // Blog and intent articles
  'blog.crumb': 'Le blog',
  'blog.title': 'Idées de sorties en Guadeloupe',
  'blog.description': 'Nos sélections de rivières, cascades et sorties guidées en Guadeloupe, par envie : en famille, pour débuter, pour les sensations ou pour se baigner.',
  'blog.intro': 'Nos sélections, par envie : en famille, pour débuter, pour les sensations ou pour se baigner.',
  'blog.read': "Lire l'article",
  'article.by': 'Par',
  'article.updated': 'Mis à jour le',
  'article.read_time': '{n} min de lecture',
  'article.answer': 'En bref',
  'article.toc': 'Sommaire',
  'article.takeaways': "L'essentiel",
  'article.selection': 'Notre sélection',
  'article.selection_n': 'Notre sélection : {n} idées',
  'article.tips': 'Bon à savoir',
  'article.before': 'Avant de partir',
  'article.before_badge': 'Attention',
  'article.faq': 'Questions fréquentes',
  'article.faq_title': '{label} : questions fréquentes',
  'article.why_title': 'Pourquoi partir avec un guide ?',
  'article.why_toc': 'Pourquoi partir avec un guide',
  'article.why_offers': 'Voir les sorties guidées',
  'article.why_about': 'Qui sommes-nous',
  'article.written_by': 'Écrit par',
  'article.authors_bio': "Guides diplômés d'État en canyoning, en Basse-Terre depuis plus de 8 ans.",
  'article.sources': 'Sources :',
  'article.related': 'Autres idées de sorties',
  'article.view_offer': 'Voir la sortie',
  'article.view_place': 'Lire la fiche',
  'article.highlights': 'Au programme',
  'article.landmarks': 'Repères',
  'article.season': 'Quand y aller',
  'article.with': 'avec {guide} · {operator}',
  'article.price': 'Prix',
  'article.price_value': '{n} €',
  'article.price_child': '{adult} € / {child} €',
  'article.access': 'Accès',
  'article.access_guide': 'Avec un guide',
  'article.access_commune': 'À se renseigner',
  'article.faq_age_q': 'À partir de quel âge ?',
  'article.faq_age_a': "Dès {age} ans pour {names}. L'âge minimum est fixé par chaque guide.",
  'article.faq_price_q': 'Combien ça coûte ?',
  'article.faq_price_a': 'À partir de {price} € par personne ({name}, avec {operator}).',
  'article.faq_price_child': 'Certaines sorties ont un tarif enfant.',
  'article.faq_gear_q': 'Quel équipement est fourni ?',
  'article.faq_gear_a': '{list}, selon la sortie.',
  'article.faq_bring_q': 'Que faut-il apporter ?',
  'article.faq_bring_a': '{list}.',

  // Filter landing pages (computed from the data: counts, guided places, access; never hand-written facts)
  'collection.by_type': 'Par type',
  'collection.by_locality': 'Par commune',
  'collection.by_criterion': 'Par critère',
  'collection.h1_type': '{plural} de Guadeloupe',
  'collection.h1_locality': '{types} à {place}',
  'collection.h1_criterion': '{label} en Guadeloupe',
  'collection.where_type': 'en Guadeloupe',
  'collection.where_locality': 'à {place}',
  'collection.noun_places': 'lieux',
  'collection.and': 'et',
  'collection.intro': 'Notre répertoire compte {n} {noun} {where}{types}. Pour chaque lieu, nous indiquons ce que nous savons de l’accès et si un guide partenaire y propose une sortie.',
  'collection.answer': 'Sur {n} {noun} {where}, {bits}.',
  'collection.answer_none': "aucun n'a encore d'accès public documenté",
  'collection.answer_guided_one': '{n} se fait avec un guide partenaire ({names})',
  'collection.answer_guided_many': '{n} se font avec un guide partenaire ({names})',
  'collection.answer_public_one': '{n} a un accès public avec parking ({names})',
  'collection.answer_public_many': '{n} ont un accès public avec parking ({names})',
  'collection.answer_closed': '{names} : accès fermé au public.',
  'collection.answer_rest_one': "Pour l'autre, nous indiquons seulement la commune : renseignez-vous avant de partir.",
  'collection.answer_rest_many': 'Pour les {n} autres, nous indiquons seulement la commune : renseignez-vous avant de partir.',
  'collection.list_eyebrow': 'Les lieux',
  'collection.list_title': '{n} {noun} {where}',
  'collection.faq_count_q': 'Combien de {noun} compte le répertoire ?',
  'collection.faq_count_a': '{n} : {names}.',
  'collection.faq_see_q': 'Que voir à {place} ?',
  'collection.faq_see_a': '{items}.',
  'collection.faq_alone_q': 'Peut-on y aller sans guide ?',
  'collection.faq_alone_public_one': "{names} a un accès public avec parking : l'itinéraire est sur la fiche.",
  'collection.faq_alone_public_many': "{names} ont un accès public avec parking : l'itinéraire est sur la fiche.",
  'collection.faq_alone_none': "Aucun lieu de cette liste n'a d'accès public documenté. Renseignez-vous avant de partir.",
  'collection.faq_alone_guide_only': '{names} : uniquement avec un guide.',
  'collection.faq_guided_q': 'Peut-on y aller avec un guide ?',
  'collection.faq_guided_yes': 'Oui, pour {items}.',
  'collection.faq_guided_item': '{name} (avec {guides})',
  'collection.faq_guided_no': "Pas pour l'instant : aucun guide partenaire ne propose ces lieux.",
  'collection.faq_closed_q': 'Des lieux sont-ils fermés ?',
  'collection.faq_closed_a': '{names} : accès fermé au public. Le détail et la source sont sur la fiche.',
  'collection.faq_fresh_q': 'Les informations sont-elles à jour ?',
  'collection.faq_fresh_a': 'Elles sont indicatives et datées sur chaque fiche. En rivière, les conditions changent vite : renseignez-vous auprès des sources officielles avant de partir.',
  'collection.faq_title': '{h1} : questions fréquentes',
  'collection.related': 'À lire aussi',
  'blog.count': '{n} articles',

  // Guide pages
  'guide.eyebrow': 'Guide · {company}',
  'guide.book': 'Réserver sur {company}',
  'guide.write': 'Écrire à {guide} sur WhatsApp',
  'guide.offers': 'Les sorties de {guide}',
  'guide.places': 'Où {guide} vous emmène',
  'guide.reviews': 'Avis sur {company}',
  'guide.rating': 'Note : {value} sur 5',
  'guide.rating_count': '{n} avis',
  'guide.description': '{name}, {role} : ses sorties guidées en Guadeloupe ({company}).',

  // Static pages
  'about.description': 'Qui sommes-nous : Pascal (Yalodé) et Quentin (Wild Canyon), guides en Guadeloupe, et pourquoi ce répertoire.',
  'legal.title': 'Mentions légales',
  'legal.description': 'Mentions légales et avertissement du site.',
  'legal.publisher': '[LEGAL_NOTICE_TEXT]',
  'privacy.title': 'Politique de confidentialité',
  'privacy.description': 'Comment ce site traite vos données.',
  'privacy.updated': 'Dernière mise à jour : {date}',
  'contact.title': 'Contact',
  'contact.description': 'Écrire à Pascal ou à Quentin, les guides derrière ce site.',
  'contact.intro': 'Une question sur un lieu ou une sortie ? Écrivez directement à Pascal ou à Quentin sur WhatsApp.',

  // Search engines, AI assistants (phase 5): computed FAQ, Markdown twins, llms.txt
  'place.faq_access_q': '{name} : comment y aller ?',
  'place.faq_access_q_to': 'Comment aller {to} ?',
  'seo.home_title': '{site} · {tagline}',
  'seo.page_title': '{title} · {site}',
  'md.page': 'Page',
  'md.updated': 'Mis à jour le',
  'md.type': 'Type',
  'md.locality': 'Commune',
  'md.area': 'Île',
  'md.access': 'Accès',
  'md.safety': 'Sécurité',
  'md.offers': 'Sorties guidées',
  'md.price': 'Prix',
  'md.book': 'Réserver',
  'md.contact': 'Contacter le guide',
  'md.sources': 'Sources',
  'md.photos': 'Crédits photo',
  'md.places': 'Lieux',
  'md.disclaimer': 'Avertissement',
  'llms.summary': "Répertoire indépendant des rivières, cascades et canyons de Guadeloupe (Basse-Terre) : accès, niveau, baignade, sécurité, et sorties avec deux guides diplômés, Pascal (Yalodé) et Quentin (Wild Canyon).",
  'llms.note_1': "Chaque lien mène à la version Markdown d'une page. Les informations sont indicatives et datées sur chaque fiche ; en rivière, les conditions changent vite.",
  'llms.note_2': "Pour les canyons et les sites fermés, nous ne publions ni coordonnées ni itinéraire : ils se font uniquement avec un guide, ou pas du tout.",
  'llms.places': 'Lieux',
  'llms.articles': 'Idées de sorties',
  'llms.collections': 'Par type et par commune',
  'llms.guides': 'Les guides',
  'llms.about': 'À propos',

  // Page not found
  'notfound.title': 'Page introuvable',
  'notfound.text': "Cette page n'existe pas ou a changé d'adresse.",
  'notfound.home': 'Voir tous les lieux',
  'notfound.blog': 'Idées de sorties',

  // Contact (WhatsApp message, CLAUDE.md §9)
  'contact.whatsapp_message': 'Bonjour {guide}, je vous écris depuis {site} au sujet {subject}.',
  'contact.subject_named': 'de « {name} »',
  'contact.subject_default': "d'une sortie",
} as const;

export type CopyKey = keyof typeof COPY_DEFAULTS;
